### PR TITLE
Reconfigure service on config changes

### PR DESCRIPTION
**Pull request by ktsakalozos**

### CODE REVIEW

**Comment by johnsca** [comment]
Seems reasonable.  +1

**Comment by johnsca** [comment]
On second thought, I think we should be explicit about what config options cause restarts, and ensure that they are documented.  In this case, it looks like it's only `heap`, so the if can be changed to:

``` python
if not data_changed('hive.config.heap', config['heap']):
```

Also, since we're doing this on several charms, I'd like to see this baked in to [layer-basic](https://github.com/juju-solutions/layer-basic) in a way similar to how the [leadership layer](https://git.launchpad.net/layer-leadership/tree/) handles leadership config settings.

**Comment by johnsca** [comment]
I went ahead and created juju-solutions/layer-basic#36 so once that gets merged, I'd like to see these PRs updated to use that.  So, it would become, instead:

``` python
@when('hadoop.ready', 'database.available', 'hive.started', 'config.changed.heap')
def reconfigure_hive(hdfs, database):
    hookenv.status_set('active', 'Configuring Hive')
    hive = Hive(get_dist_config())
    hive.stop()
    hive.configure_hive(database)
    hive.start()
    hookenv.status_set('active', 'Ready')
```

**Comment by ktsakalozos** [comment]
This looks great!

**Pull request merged**
